import { APP_STATE_STORAGE_KEY } from '@/repositories/LocalAppRepository';
import {
  APP_MUTATION_OUTBOX_RECOVERY_STORAGE_KEY,
  BODY_MEASUREMENT_SYNC_METADATA_STORAGE_KEY,
  CUSTOM_EXERCISE_SYNC_METADATA_STORAGE_KEY,
  FITNESS_PROFILE_SYNC_METADATA_STORAGE_KEY,
  FOOD_ENTRY_SYNC_METADATA_STORAGE_KEY,
  LOCAL_STATE_DIAGNOSTICS_STORAGE_KEY,
  MEAL_TEMPLATE_SYNC_METADATA_STORAGE_KEY,
  NUTRITION_TARGET_SYNC_METADATA_STORAGE_KEY,
  OFFLINE_SYNC_QUEUE_STORAGE_KEY,
  SAFETY_RECOVERY_REVIEW_STORAGE_KEY,
  SAFETY_RECOVERY_SYNC_METADATA_STORAGE_KEY,
  SYNC_CONFLICT_RESOLUTION_INTENT_STORAGE_KEY,
  SYNC_CONFLICT_STORAGE_KEY,
  SYNC_CURSOR_STORAGE_KEY,
  TRAINING_PROGRAM_SYNC_METADATA_STORAGE_KEY,
  WEIGHT_SYNC_METADATA_STORAGE_KEY,
  WORKOUT_SAFETY_ACKNOWLEDGEMENT_STORAGE_KEY,
  WORKOUT_SESSION_SYNC_METADATA_STORAGE_KEY,
  WORKOUT_TEMPLATE_SYNC_METADATA_STORAGE_KEY,
} from '@/storage';

export const APPLICATION_STATE_STORAGE_KEYS = [APP_STATE_STORAGE_KEY] as const;

export const SYNC_METADATA_STORAGE_KEYS = [
  BODY_MEASUREMENT_SYNC_METADATA_STORAGE_KEY,
  CUSTOM_EXERCISE_SYNC_METADATA_STORAGE_KEY,
  FITNESS_PROFILE_SYNC_METADATA_STORAGE_KEY,
  FOOD_ENTRY_SYNC_METADATA_STORAGE_KEY,
  MEAL_TEMPLATE_SYNC_METADATA_STORAGE_KEY,
  NUTRITION_TARGET_SYNC_METADATA_STORAGE_KEY,
  SAFETY_RECOVERY_SYNC_METADATA_STORAGE_KEY,
  TRAINING_PROGRAM_SYNC_METADATA_STORAGE_KEY,
  WEIGHT_SYNC_METADATA_STORAGE_KEY,
  WORKOUT_SESSION_SYNC_METADATA_STORAGE_KEY,
  WORKOUT_TEMPLATE_SYNC_METADATA_STORAGE_KEY,
] as const;

export const SYNC_RECOVERY_STORAGE_KEYS = [
  APP_MUTATION_OUTBOX_RECOVERY_STORAGE_KEY,
  OFFLINE_SYNC_QUEUE_STORAGE_KEY,
  SYNC_CURSOR_STORAGE_KEY,
] as const;

export const CONFLICT_STORAGE_KEYS = [
  SYNC_CONFLICT_STORAGE_KEY,
  SYNC_CONFLICT_RESOLUTION_INTENT_STORAGE_KEY,
] as const;

export const SAFETY_STORAGE_KEYS = [
  SAFETY_RECOVERY_REVIEW_STORAGE_KEY,
  WORKOUT_SAFETY_ACKNOWLEDGEMENT_STORAGE_KEY,
] as const;

export const LOCAL_DIAGNOSTIC_STORAGE_KEYS = [
  LOCAL_STATE_DIAGNOSTICS_STORAGE_KEY,
] as const;

export const ACCOUNT_SCOPED_ASYNC_STORAGE_KEYS = [
  ...APPLICATION_STATE_STORAGE_KEYS,
  ...SYNC_METADATA_STORAGE_KEYS,
  ...SYNC_RECOVERY_STORAGE_KEYS,
  ...CONFLICT_STORAGE_KEYS,
  ...SAFETY_STORAGE_KEYS,
  ...LOCAL_DIAGNOSTIC_STORAGE_KEYS,
] as const;
