import { StyleSheet } from 'react-native';

import { Colors, Radii, Spacing, Typography } from '@/constants/theme';

export const createProgramBuilderStyles = (colors: typeof Colors.dark) =>
  StyleSheet.create({
    blockMeta: {
      color: colors.textSecondary,
      fontSize: Typography.callout.fontSize,
      lineHeight: Typography.callout.lineHeight,
    },
    blockTitle: {
      color: colors.textPrimary,
      fontSize: Typography.bodyEmphasized.fontSize,
      fontWeight: '900',
      lineHeight: Typography.bodyEmphasized.lineHeight,
    },
    collapsibleCopy: {
      flex: 1,
      gap: 4,
      minWidth: 0,
    },
    collapsibleHeader: {
      paddingBottom: Spacing.two,
    },
    collapsibleHeaderRow: {
      alignItems: 'flex-start',
      flexDirection: 'row',
      gap: Spacing.two,
      justifyContent: 'space-between',
    },
    compactAction: {
      alignItems: 'center',
      borderCurve: 'continuous',
      borderRadius: Radii.pill,
      justifyContent: 'center',
      minHeight: 44,
      minWidth: 88,
      paddingHorizontal: Spacing.three,
      paddingVertical: Spacing.two,
    },
    compactActionLabelPrimary: {
      color: colors.textOnAccent,
      fontSize: Typography.caption.fontSize,
      fontWeight: '900',
      lineHeight: Typography.caption.lineHeight,
    },
    compactActionLabelSecondary: {
      color: colors.textPrimary,
      fontSize: Typography.caption.fontSize,
      fontWeight: '800',
      lineHeight: Typography.caption.lineHeight,
    },
    compactActionPressed: {
      opacity: 0.85,
    },
    compactActionPrimary: {
      backgroundColor: colors.accent,
    },
    compactActionSecondary: {
      backgroundColor: colors.surfaceSecondary,
      borderColor: colors.borderSubtle,
      borderWidth: StyleSheet.hairlineWidth,
    },
    dayActionGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.two,
    },
    dayBlock: {
      gap: Spacing.two,
      paddingVertical: Spacing.one,
    },
    dayExpanded: {
      gap: Spacing.three,
      paddingLeft: Spacing.two,
    },
    dayHeader: {
      alignItems: 'flex-start',
      flexDirection: 'row',
      gap: Spacing.two,
      justifyContent: 'space-between',
      minHeight: 56,
      paddingVertical: Spacing.two,
    },
    dayHeaderCopy: {
      flex: 1,
      gap: 4,
      minWidth: 0,
    },
    dayList: {
      gap: Spacing.two,
    },
    dayTitle: {
      color: colors.textPrimary,
      fontSize: Typography.bodyEmphasized.fontSize,
      fontWeight: '900',
      lineHeight: Typography.bodyEmphasized.lineHeight,
    },
    dayTopLine: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: Spacing.two,
    },
    dayWorkoutName: {
      color: colors.textSecondary,
      fontSize: Typography.callout.fontSize,
      lineHeight: Typography.callout.lineHeight,
    },
    frequencyLabel: {
      color: colors.textPrimary,
      fontSize: Typography.callout.fontSize,
      fontWeight: '800',
      lineHeight: Typography.callout.lineHeight,
    },
    frequencyList: {
      gap: 6,
    },
    frequencyRow: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: Spacing.two,
    },
    frequencyValue: {
      color: colors.textSecondary,
      fontSize: Typography.callout.fontSize,
      lineHeight: Typography.callout.lineHeight,
    },
    input: {
      backgroundColor: colors.surfaceSecondary,
      borderColor: colors.borderSubtle,
      borderCurve: 'continuous',
      borderRadius: Radii.medium,
      borderWidth: StyleSheet.hairlineWidth,
      color: colors.textPrimary,
      fontSize: 16,
      minHeight: 48,
      paddingHorizontal: Spacing.three,
      paddingVertical: 12,
    },
    inputGroup: {
      gap: 4,
    },
    inputLabel: {
      color: colors.textSecondary,
      fontSize: Typography.label.fontSize,
      fontWeight: Typography.label.fontWeight,
      lineHeight: Typography.label.lineHeight,
    },
    metricDetail: {
      color: colors.textSecondary,
      fontSize: Typography.caption.fontSize,
      lineHeight: Typography.caption.lineHeight,
    },
    metricGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.two,
    },
    metricLabel: {
      color: colors.textSecondary,
      fontSize: Typography.caption.fontSize,
      fontWeight: '800',
      letterSpacing: 0.3,
      textTransform: 'uppercase',
    },
    metricTile: {
      backgroundColor: colors.backgroundSelected,
      borderColor: colors.borderSubtle,
      borderCurve: 'continuous',
      borderRadius: Radii.large,
      borderWidth: StyleSheet.hairlineWidth,
      flexBasis: '48%',
      flexGrow: 1,
      gap: 4,
      minWidth: 140,
      padding: Spacing.three,
    },
    metricValue: {
      color: colors.textPrimary,
      fontSize: Typography.cardTitle.fontSize,
      fontWeight: '900',
      lineHeight: Typography.cardTitle.lineHeight,
    },
    notesInput: {
      backgroundColor: colors.surfaceSecondary,
      borderColor: colors.borderSubtle,
      borderCurve: 'continuous',
      borderRadius: Radii.medium,
      borderWidth: StyleSheet.hairlineWidth,
      color: colors.textPrimary,
      fontSize: 16,
      minHeight: 88,
      paddingHorizontal: Spacing.three,
      paddingVertical: Spacing.three,
      textAlignVertical: 'top',
    },
    pill: {
      alignItems: 'center',
      backgroundColor: colors.surfaceSecondary,
      borderColor: colors.borderSubtle,
      borderCurve: 'continuous',
      borderRadius: Radii.pill,
      borderWidth: StyleSheet.hairlineWidth,
      minHeight: 44,
      justifyContent: 'center',
      paddingHorizontal: Spacing.three,
      paddingVertical: Spacing.two,
    },
    pillLabel: {
      color: colors.textSecondary,
      fontSize: Typography.caption.fontSize,
      fontWeight: '800',
      lineHeight: Typography.caption.lineHeight,
      textTransform: 'capitalize',
    },
    pillLabelSelected: {
      color: colors.textPrimary,
    },
    pillPressed: {
      opacity: 0.88,
    },
    pillRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.two,
    },
    pillSelected: {
      backgroundColor: colors.backgroundSelected,
      borderColor: colors.accentSoft,
    },
    progressionGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.two,
    },
    progressionItem: {
      flexBasis: '48%',
      flexGrow: 1,
      gap: 4,
      minWidth: 140,
    },
    reviewBlock: {
      gap: Spacing.two,
      paddingTop: Spacing.one,
    },
    reviewText: {
      color: colors.textSecondary,
      fontSize: Typography.callout.fontSize,
      lineHeight: Typography.callout.lineHeight,
    },
    rowDivider: {
      borderTopColor: colors.borderSubtle,
      borderTopWidth: StyleSheet.hairlineWidth,
    },
    scheduleCopy: {
      flex: 1,
      gap: 2,
      minWidth: 0,
    },
    sectionCard: {
      gap: Spacing.three,
      padding: Spacing.four,
    },
    sectionHeading: {
      alignItems: 'flex-start',
      flexDirection: 'row',
      gap: Spacing.two,
      justifyContent: 'space-between',
    },
    sectionHeadingCopy: {
      flex: 1,
      gap: 4,
      minWidth: 0,
    },
    sectionHeadingPressed: {
      opacity: 0.9,
    },
    sectionSubtitle: {
      color: colors.textSecondary,
      fontSize: Typography.callout.fontSize,
      lineHeight: Typography.callout.lineHeight,
    },
    sectionTitle: {
      color: colors.textPrimary,
      fontSize: Typography.cardTitle.fontSize,
      fontWeight: '900',
      lineHeight: Typography.cardTitle.lineHeight,
    },
    sectionToggle: {
      color: colors.accent,
      fontSize: Typography.cardTitle.fontSize,
      fontWeight: '900',
      lineHeight: Typography.cardTitle.lineHeight,
    },
    selectedTemplateCopy: {
      flex: 1,
      gap: 2,
      minWidth: 0,
    },
    selectedTemplateList: {
      borderColor: colors.borderSubtle,
      borderCurve: 'continuous',
      borderRadius: Radii.large,
      borderWidth: StyleSheet.hairlineWidth,
      overflow: 'hidden',
    },
    selectedTemplateMeta: {
      color: colors.textSecondary,
      fontSize: Typography.callout.fontSize,
      lineHeight: Typography.callout.lineHeight,
    },
    selectedTemplateRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: Spacing.two,
      justifyContent: 'space-between',
      minHeight: 54,
      paddingHorizontal: Spacing.three,
      paddingVertical: Spacing.two,
    },
    selectedTemplateTitle: {
      color: colors.textPrimary,
      fontSize: Typography.bodyEmphasized.fontSize,
      fontWeight: '800',
      lineHeight: Typography.bodyEmphasized.lineHeight,
    },
    selectedTemplatesBlock: {
      gap: Spacing.two,
    },
    stack: {
      gap: Spacing.three,
    },
    statePill: {
      alignItems: 'center',
      borderCurve: 'continuous',
      borderRadius: Radii.pill,
      justifyContent: 'center',
      minHeight: 28,
      paddingHorizontal: Spacing.two,
    },
    statePillRest: {
      backgroundColor: colors.backgroundSelected,
    },
    statePillText: {
      fontSize: Typography.caption.fontSize,
      fontWeight: '800',
      lineHeight: Typography.caption.lineHeight,
    },
    statePillTextRest: {
      color: colors.textSecondary,
    },
    statePillTextWorkout: {
      color: colors.accent,
    },
    statePillWorkout: {
      backgroundColor: colors.accentSoft,
    },
    templateBank: {
      gap: Spacing.two,
    },
    templateBankCopy: {
      flex: 1,
      gap: 2,
      minWidth: 0,
    },
    templateBankHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: Spacing.two,
    },
    templateBankMeta: {
      color: colors.textSecondary,
      fontSize: Typography.callout.fontSize,
      lineHeight: Typography.callout.lineHeight,
    },
    templateBankRow: {
      alignItems: 'center',
      backgroundColor: colors.surfaceSecondary,
      borderColor: colors.borderSubtle,
      borderCurve: 'continuous',
      borderRadius: Radii.large,
      borderWidth: StyleSheet.hairlineWidth,
      flexDirection: 'row',
      gap: Spacing.two,
      minHeight: 56,
      paddingHorizontal: Spacing.three,
      paddingVertical: Spacing.two,
    },
    templateBankRowSelected: {
      backgroundColor: colors.backgroundSelected,
      borderColor: colors.accentSoft,
    },
    templateBankTitle: {
      color: colors.textPrimary,
      fontSize: Typography.bodyEmphasized.fontSize,
      fontWeight: '800',
      lineHeight: Typography.bodyEmphasized.lineHeight,
    },
    templatePickerHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: Spacing.two,
    },
    weekSectionSpacer: {},
  });
