import { StyleSheet } from 'react-native';

import { Colors, MaxContentWidth, Radii, Spacing, Typography } from '@/constants/theme';

export const createAddFoodStyles = (colors: typeof Colors.dark) =>
  StyleSheet.create({
    backButton: {
      alignItems: 'flex-start',
      minHeight: 44,
      justifyContent: 'center',
      paddingHorizontal: Spacing.one,
      width: 72,
    },
    backButtonText: {
      color: colors.accent,
      fontSize: 15,
      fontWeight: '800',
    },
    clearButton: {
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 44,
      width: 44,
    },
    clearButtonText: {
      color: colors.textSecondary,
      fontSize: 24,
      fontWeight: '900',
      lineHeight: 24,
    },
    container: {
      gap: Spacing.three,
      maxWidth: MaxContentWidth,
      width: '100%',
    },
    content: {
      backgroundColor: colors.background,
      alignItems: 'center',
      flexGrow: 1,
      padding: Spacing.three,
    },
    emptyBlock: {
      alignItems: 'flex-start',
      gap: Spacing.two,
      paddingTop: Spacing.one,
    },
    emptyStateText: {
      color: colors.textSecondary,
      fontSize: Typography.body.fontSize,
      lineHeight: Typography.body.lineHeight,
    },
    formErrorText: {
      color: colors.error,
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 16,
    },
    footer: {},
    grid: {
      flexDirection: 'row',
      gap: Spacing.two,
    },
    headerCopy: {
      alignItems: 'center',
      flex: 1,
      gap: 2,
    },
    headerRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: Spacing.one,
    },
    quietActionButton: {
      alignItems: 'center',
      minHeight: 44,
      justifyContent: 'center',
      paddingHorizontal: Spacing.one,
    },
    quietActionRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.three,
    },
    quietActionText: {
      color: colors.textSecondary,
      fontSize: 13,
      fontWeight: '800',
    },
    readOnlyInput: {
      color: colors.textMuted,
    },
    headerSpacer: {
      width: 72,
    },
    iconButton: {
      alignItems: 'center',
      borderColor: colors.borderSubtle,
      borderCurve: 'continuous',
      borderRadius: 999,
      borderWidth: StyleSheet.hairlineWidth,
      height: 44,
      justifyContent: 'center',
      width: 44,
    },
    iconButtonText: {
      color: colors.textPrimary,
      fontSize: 18,
      fontWeight: '900',
      lineHeight: 18,
    },
    input: {
      backgroundColor: colors.surfaceSecondary,
      borderColor: colors.borderSubtle,
      borderCurve: 'continuous',
      borderRadius: Radii.large,
      borderWidth: StyleSheet.hairlineWidth,
      color: colors.textPrimary,
      fontSize: 15,
      minHeight: 44,
      paddingHorizontal: Spacing.three,
      paddingVertical: Spacing.two,
    },
    inlineForm: {
      gap: Spacing.two,
    },
    listGap: {
      gap: Spacing.two,
    },
    messageBanner: {
      backgroundColor: colors.surfaceSecondary,
      borderColor: colors.borderSubtle,
      borderCurve: 'continuous',
      borderRadius: Radii.large,
      borderWidth: StyleSheet.hairlineWidth,
      padding: Spacing.two,
    },
    messageText: {
      color: colors.textPrimary,
      fontSize: 13,
      fontWeight: '700',
    },
    rowActions: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: Spacing.one,
    },
    scanButton: {
      alignItems: 'center',
      backgroundColor: colors.surfaceSecondary,
      borderColor: colors.borderSubtle,
      borderCurve: 'continuous',
      borderRadius: Radii.large,
      borderWidth: StyleSheet.hairlineWidth,
      justifyContent: 'center',
      minHeight: 44,
      paddingHorizontal: Spacing.two,
    },
    scanButtonText: {
      color: colors.textPrimary,
      fontSize: 13,
      fontWeight: '800',
    },
    scannerActions: {
      gap: Spacing.two,
    },
    scannerBarcodeText: {
      color: colors.textMuted,
      fontSize: 12,
      lineHeight: 16,
    },
    scannerCamera: {
      flex: 1,
    },
    scannerCameraWrap: {
      backgroundColor: colors.surfaceSecondary,
      borderColor: colors.borderSubtle,
      borderCurve: 'continuous',
      borderRadius: Radii.large,
      borderWidth: StyleSheet.hairlineWidth,
      flex: 1,
      overflow: 'hidden',
    },
    scannerCloseButton: {
      alignItems: 'flex-start',
      justifyContent: 'center',
      minHeight: 44,
      paddingHorizontal: Spacing.one,
      width: 72,
    },
    scannerCloseText: {
      color: colors.accent,
      fontSize: 15,
      fontWeight: '800',
    },
    scannerFrame: {
      borderColor: colors.accent,
      borderCurve: 'continuous',
      borderRadius: Radii.large,
      borderWidth: 2,
      height: 120,
      width: '82%',
    },
    scannerHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: Spacing.one,
    },
    scannerHeaderSpacer: {
      width: 72,
    },
    scannerInstruction: {
      color: colors.textPrimary,
      fontSize: 13,
      fontWeight: '800',
      marginTop: Spacing.two,
      textAlign: 'center',
    },
    scannerManualButton: {
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 44,
    },
    scannerManualForm: {
      backgroundColor: colors.surfacePrimary,
      borderColor: colors.borderSubtle,
      borderCurve: 'continuous',
      borderRadius: Radii.large,
      borderWidth: StyleSheet.hairlineWidth,
      gap: Spacing.two,
      padding: Spacing.three,
    },
    scannerManualHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: Spacing.two,
      justifyContent: 'space-between',
    },
    scannerManualText: {
      color: colors.textSecondary,
      fontSize: 13,
      fontWeight: '800',
    },
    scannerOverlay: {
      ...StyleSheet.absoluteFill,
      alignItems: 'center',
      justifyContent: 'center',
      padding: Spacing.three,
    },
    scannerPermissionCard: {
      backgroundColor: colors.surfacePrimary,
      borderColor: colors.borderSubtle,
      borderCurve: 'continuous',
      borderRadius: Radii.large,
      borderWidth: StyleSheet.hairlineWidth,
      gap: Spacing.two,
      padding: Spacing.three,
    },
    scannerPermissionText: {
      color: colors.textSecondary,
      fontSize: 13,
      lineHeight: 18,
    },
    scannerPermissionTitle: {
      color: colors.textPrimary,
      fontSize: 18,
      fontWeight: '900',
    },
    scannerScreen: {
      backgroundColor: colors.background,
      flex: 1,
      gap: Spacing.three,
      padding: Spacing.three,
      paddingTop: Spacing.six,
    },
    scannerStatusCard: {
      backgroundColor: colors.surfacePrimary,
      borderColor: colors.borderSubtle,
      borderCurve: 'continuous',
      borderRadius: Radii.large,
      borderWidth: StyleSheet.hairlineWidth,
      gap: Spacing.two,
      padding: Spacing.three,
    },
    scannerStatusText: {
      color: colors.textPrimary,
      fontSize: 14,
      fontWeight: '800',
      lineHeight: 18,
    },
    scannerTitle: {
      color: colors.textPrimary,
      flex: 1,
      fontSize: 18,
      fontWeight: '900',
      textAlign: 'center',
    },
    resultAttribution: {
      color: colors.textMuted,
      fontSize: 11,
      lineHeight: 15,
      paddingTop: Spacing.one,
    },
    searchInput: {
      backgroundColor: colors.surfaceSecondary,
      borderColor: colors.borderSubtle,
      borderCurve: 'continuous',
      borderRadius: Radii.large,
      borderWidth: StyleSheet.hairlineWidth,
      color: colors.textPrimary,
      flex: 1,
      fontSize: 15,
      minHeight: 44,
      paddingHorizontal: Spacing.three,
      paddingVertical: Spacing.two,
    },
    searchRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: Spacing.one,
      marginBottom: Spacing.two,
    },
    secondaryActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.two,
    },
    screen: {
      backgroundColor: colors.background,
      flex: 1,
    },
    sectionHeader: {
      marginBottom: Spacing.two,
    },
    sectionTitle: {
      color: colors.textPrimary,
      fontSize: 18,
      fontWeight: '800',
    },
    sheet: {
      backgroundColor: colors.surfacePrimary,
      borderColor: colors.borderSubtle,
      borderCurve: 'continuous',
      borderTopLeftRadius: Radii.xlarge,
      borderTopRightRadius: Radii.xlarge,
      borderTopWidth: StyleSheet.hairlineWidth,
      gap: Spacing.two,
      maxWidth: MaxContentWidth,
      padding: Spacing.three,
      width: '100%',
    },
    sheetAttribution: {
      color: colors.textMuted,
      fontSize: 11,
      lineHeight: 15,
    },
    sheetBackdrop: {
      alignItems: 'center',
      bottom: 0,
      left: 0,
      position: 'absolute',
      right: 0,
      top: 0,
      justifyContent: 'flex-end',
    },
    sheetClose: {
      alignItems: 'center',
      backgroundColor: colors.surfaceSecondary,
      borderColor: colors.borderSubtle,
      borderCurve: 'continuous',
      borderRadius: 999,
      borderWidth: StyleSheet.hairlineWidth,
      height: 44,
      justifyContent: 'center',
      width: 44,
    },
    sheetCloseText: {
      color: colors.textPrimary,
      fontSize: 24,
      fontWeight: '900',
      lineHeight: 24,
    },
    sheetField: {
      gap: Spacing.one,
    },
    sheetHeader: {
      alignItems: 'flex-start',
      flexDirection: 'row',
      gap: Spacing.two,
      justifyContent: 'space-between',
    },
    sheetHint: {
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 16,
    },
    sheetScrim: {
      ...StyleSheet.absoluteFill,
      backgroundColor: 'rgba(0, 0, 0, 0.4)',
    },
    helperText: {
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 16,
    },
    sheetInput: {
      backgroundColor: colors.surfaceSecondary,
      borderColor: colors.borderSubtle,
      borderCurve: 'continuous',
      borderRadius: Radii.large,
      borderWidth: StyleSheet.hairlineWidth,
      color: colors.textPrimary,
      fontSize: 16,
      minHeight: 48,
      paddingHorizontal: Spacing.three,
    },
    sheetLabel: {
      color: colors.textSecondary,
      fontSize: 12,
      fontWeight: '800',
      textTransform: 'uppercase',
    },
    sheetMeta: {
      color: colors.textSecondary,
      fontSize: 13,
      lineHeight: 18,
    },
    sheetSubtitle: {
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 16,
    },
    sheetTitle: {
      color: colors.textPrimary,
      fontSize: 18,
      fontWeight: '900',
    },
    sheetTotalLine: {
      color: colors.textPrimary,
      fontSize: 14,
      fontWeight: '800',
    },
    sheetTotals: {
      backgroundColor: colors.surfaceSecondary,
      borderColor: colors.borderSubtle,
      borderCurve: 'continuous',
      borderRadius: Radii.large,
      borderWidth: StyleSheet.hairlineWidth,
      padding: Spacing.two,
    },
    nutritionGrid: {
      gap: Spacing.two,
    },
    summaryCalories: {
      color: colors.textPrimary,
      fontSize: 15,
      fontWeight: '900',
      fontVariant: ['tabular-nums'],
    },
    summaryCopy: {
      color: colors.textSecondary,
      fontSize: 12,
    },
    summaryPill: {
      alignItems: 'center',
      backgroundColor: colors.surfaceSecondary,
      borderColor: colors.borderSubtle,
      borderCurve: 'continuous',
      borderRadius: Radii.large,
      borderWidth: StyleSheet.hairlineWidth,
      flexDirection: 'row',
      justifyContent: 'space-between',
      padding: Spacing.three,
    },
    summaryTitle: {
      color: colors.textPrimary,
      fontSize: 14,
      fontWeight: '800',
    },
    suggestionChip: {
      backgroundColor: colors.surfaceSecondary,
      borderColor: colors.borderSubtle,
      borderCurve: 'continuous',
      borderRadius: Radii.large,
      borderWidth: StyleSheet.hairlineWidth,
      minHeight: 36,
      justifyContent: 'center',
      paddingHorizontal: Spacing.two,
      paddingVertical: Spacing.one,
    },
    suggestionList: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.one,
      marginBottom: Spacing.two,
    },
    suggestionText: {
      color: colors.textSecondary,
      fontSize: 13,
      fontWeight: '700',
    },
    subtitle: {
      color: colors.textSecondary,
      fontSize: 12,
      fontWeight: '700',
    },
    title: {
      color: colors.textPrimary,
      fontSize: 20,
      fontWeight: '900',
    },
    unitToggle: {
      backgroundColor: colors.surfaceSecondary,
      borderColor: colors.borderSubtle,
      borderCurve: 'continuous',
      borderRadius: Radii.large,
      borderWidth: StyleSheet.hairlineWidth,
      flexDirection: 'row',
      gap: Spacing.one,
      padding: Spacing.one,
    },
    unitToggleOption: {
      alignItems: 'center',
      borderRadius: Radii.medium,
      flex: 1,
      justifyContent: 'center',
      minHeight: 40,
    },
    unitToggleOptionActive: {
      backgroundColor: colors.accent,
    },
    unitToggleText: {
      color: colors.textSecondary,
      fontSize: 13,
      fontWeight: '800',
    },
    unitToggleTextActive: {
      color: colors.background,
    },
  });
