import type { SupportedLocale } from '@/localization';

export const getShareWorkoutCopy = (locale: SupportedLocale) =>
  locale === 'ru'
    ? {
        title: 'Поделиться тренировкой',
        subtitle: 'Выберите только те данные, которые хотите опубликовать.',
        caption: 'Подпись',
        captionPlaceholder: 'Что хотите рассказать об этой тренировке?',
        preview: 'Предпросмотр',
        fields: 'Публичные данные',
        workoutTitle: 'Название тренировки',
        duration: 'Продолжительность',
        exercises: 'Упражнения',
        sets: 'Подходы',
        load: 'Вес',
        repetitions: 'Повторения',
        rpe: 'RPE',
        volume: 'Общий объём',
        minutes: (count: number) => `${count} мин`,
        exerciseCount: (count: number) => `${count} упр.`,
        setCount: (count: number) => `${count} подх.`,
        volumeValue: (value: number) => `${Math.round(value)} кг`,
        detailsHidden: 'Детали подходов скрыты',
        publish: 'Опубликовать',
        publishTitle: 'Опубликовать тренировку?',
        publishBody:
          'Будет создан отдельный неизменяемый публичный снимок. Изменения личной тренировки не изменят публикацию.',
        publishConfirm: 'Опубликовать',
        publishing: 'Синхронизация и публикация…',
        successTitle: 'Тренировка опубликована',
        successBody: 'Публикация сохранена в вашем социальном профиле.',
        done: 'Готово',
        signInTitle: 'Нужен аккаунт',
        signInBody: 'Войдите, чтобы синхронизировать и опубликовать тренировку.',
        signIn: 'Войти',
        profileTitle: 'Создайте социальный профиль',
        profileBody: 'Перед первой публикацией выберите username и видимость профиля.',
        createProfile: 'Создать профиль',
        missingTitle: 'Тренировка не найдена',
        missingBody: 'Локальная завершённая тренировка больше недоступна.',
        sourceNotReady:
          'Тренировка ещё не появилась на сервере. Проверьте подключение и повторите публикацию.',
        offline: 'Нет соединения. Подключитесь к интернету и повторите попытку.',
        sessionExpired: 'Сессия истекла. Войдите снова.',
        unavailable: 'Эту тренировку нельзя опубликовать с выбранными данными.',
        genericError: 'Не удалось опубликовать тренировку. Повторите попытку.',
        emptyError: 'Выберите хотя бы одно поле или добавьте подпись.',
        retry: 'Повторить',
        back: 'Назад',
      }
    : {
        title: 'Share workout',
        subtitle: 'Choose only the details you want to make public.',
        caption: 'Caption',
        captionPlaceholder: 'What would you like to say about this workout?',
        preview: 'Preview',
        fields: 'Public details',
        workoutTitle: 'Workout title',
        duration: 'Duration',
        exercises: 'Exercises',
        sets: 'Sets',
        load: 'Load',
        repetitions: 'Repetitions',
        rpe: 'RPE',
        volume: 'Total volume',
        minutes: (count: number) => `${count} min`,
        exerciseCount: (count: number) => `${count} exercises`,
        setCount: (count: number) => `${count} sets`,
        volumeValue: (value: number) => `${Math.round(value)} kg`,
        detailsHidden: 'Set details hidden',
        publish: 'Publish',
        publishTitle: 'Publish this workout?',
        publishBody:
          'A separate immutable public snapshot will be created. Later edits to the private workout will not change the post.',
        publishConfirm: 'Publish',
        publishing: 'Syncing and publishing…',
        successTitle: 'Workout published',
        successBody: 'The post is now saved to your social profile.',
        done: 'Done',
        signInTitle: 'Account required',
        signInBody: 'Sign in to synchronize and publish this workout.',
        signIn: 'Sign in',
        profileTitle: 'Create a social profile',
        profileBody: 'Choose a username and profile visibility before your first post.',
        createProfile: 'Create profile',
        missingTitle: 'Workout not found',
        missingBody: 'The completed local workout is no longer available.',
        sourceNotReady:
          'The workout has not reached the server yet. Check your connection and retry publishing.',
        offline: 'You are offline. Reconnect and try again.',
        sessionExpired: 'Your session expired. Sign in again.',
        unavailable: 'This workout cannot be published with the selected details.',
        genericError: 'The workout could not be published. Try again.',
        emptyError: 'Select at least one field or add a caption.',
        retry: 'Retry',
        back: 'Back',
      };
