import type { SupportedLocale } from '@/localization';

const en = {
  findAction: 'Find profile',
  findEyebrow: 'SOCIAL',
  findTitle: 'Find a profile',
  findSubtitle: 'Open a social profile by its exact username.',
  username: 'Username',
  usernamePlaceholder: 'coach_ivan',
  usernameHelp: 'Enter 3–30 letters, numbers, or underscores.',
  validationRequired: 'Enter a username.',
  validationFormat: 'Use 3–30 letters, numbers, or underscores.',
  openProfile: 'Open profile',
  signInTitle: 'Sign in required',
  signInBody: 'Sign in before viewing or following social profiles.',
  signInAction: 'Sign in',
  profileEyebrow: 'SOCIAL PROFILE',
  loading: 'Loading profile…',
  retry: 'Retry',
  notFoundTitle: 'Profile not found',
  notFoundBody: 'Check the username and try again.',
  privateTitle: 'Private profile',
  privateBody: 'This user approves follow requests before their profile becomes visible.',
  blockedTitle: 'Profile unavailable',
  blockedBody: 'This profile cannot be viewed because a block is active.',
  loadErrorTitle: 'Could not load profile',
  loadError: 'The profile could not be loaded right now.',
  visibilityPublic: 'PUBLIC',
  visibilityPrivate: 'PRIVATE',
  ownProfile: 'This is your social profile.',
  editOwnProfile: 'Edit social profile',
  following: 'Following',
  followsYou: 'Follows you',
  requestPending: 'Request pending',
  requestedToFollow: 'Requested to follow you',
  follow: 'Follow',
  requestFollow: 'Request to follow',
  unfollow: 'Unfollow',
  cancelRequest: 'Cancel request',
  approveRequest: 'Approve request',
  rejectRequest: 'Reject request',
  block: 'Block profile',
  unblock: 'Unblock profile',
  blockTitle: 'Block this profile?',
  blockBody: 'Following and pending requests between both profiles will be removed.',
  blockConfirm: 'Block',
  actionErrorOffline: 'Connect to the internet and try again.',
  actionErrorSession: 'Your session expired. Sign in again.',
  actionErrorUnavailable: 'This social action is not available.',
  actionErrorGeneric: 'The social action could not be completed. Try again.',
  noBio: 'No bio added.',
} as const;

export type SocialPublicProfileCopy = Record<keyof typeof en, string>;

const ru: SocialPublicProfileCopy = {
  findAction: 'Найти профиль',
  findEyebrow: 'СОЦИАЛЬНЫЙ ПРОФИЛЬ',
  findTitle: 'Найти профиль',
  findSubtitle: 'Откройте социальный профиль по точному имени пользователя.',
  username: 'Имя пользователя',
  usernamePlaceholder: 'coach_ivan',
  usernameHelp: 'Введите от 3 до 30 букв, цифр или символов подчёркивания.',
  validationRequired: 'Введите имя пользователя.',
  validationFormat: 'Используйте от 3 до 30 букв, цифр или символов подчёркивания.',
  openProfile: 'Открыть профиль',
  signInTitle: 'Требуется вход',
  signInBody: 'Войдите, чтобы просматривать социальные профили и подписываться.',
  signInAction: 'Войти',
  profileEyebrow: 'СОЦИАЛЬНЫЙ ПРОФИЛЬ',
  loading: 'Загрузка профиля…',
  retry: 'Повторить',
  notFoundTitle: 'Профиль не найден',
  notFoundBody: 'Проверьте имя пользователя и повторите попытку.',
  privateTitle: 'Закрытый профиль',
  privateBody: 'Пользователь подтверждает запросы на подписку перед открытием профиля.',
  blockedTitle: 'Профиль недоступен',
  blockedBody: 'Профиль нельзя просмотреть из-за активной блокировки.',
  loadErrorTitle: 'Не удалось загрузить профиль',
  loadError: 'Сейчас не удалось загрузить профиль.',
  visibilityPublic: 'ПУБЛИЧНЫЙ',
  visibilityPrivate: 'ЗАКРЫТЫЙ',
  ownProfile: 'Это ваш социальный профиль.',
  editOwnProfile: 'Изменить социальный профиль',
  following: 'Вы подписаны',
  followsYou: 'Подписан на вас',
  requestPending: 'Запрос отправлен',
  requestedToFollow: 'Запросил подписку на вас',
  follow: 'Подписаться',
  requestFollow: 'Отправить запрос',
  unfollow: 'Отписаться',
  cancelRequest: 'Отменить запрос',
  approveRequest: 'Подтвердить запрос',
  rejectRequest: 'Отклонить запрос',
  block: 'Заблокировать профиль',
  unblock: 'Разблокировать профиль',
  blockTitle: 'Заблокировать профиль?',
  blockBody: 'Подписки и ожидающие запросы между профилями будут удалены.',
  blockConfirm: 'Заблокировать',
  actionErrorOffline: 'Подключитесь к интернету и повторите попытку.',
  actionErrorSession: 'Сессия истекла. Войдите снова.',
  actionErrorUnavailable: 'Это социальное действие недоступно.',
  actionErrorGeneric: 'Не удалось выполнить действие. Повторите попытку.',
  noBio: 'Описание не добавлено.',
};

export const getSocialPublicProfileCopy = (
  locale: SupportedLocale,
): SocialPublicProfileCopy => (locale === 'ru' ? ru : en);
