import type { SupportedLocale } from '@/localization';

const en = {
  postsAction: 'Workout posts',
  listEyebrow: 'SOCIAL WORKOUTS',
  listTitle: 'Workout posts',
  listSubtitle: 'Published workout snapshots from this profile.',
  detailEyebrow: 'WORKOUT POST',
  loading: 'Loading workout posts…',
  loadingPost: 'Loading workout post…',
  loadMore: 'Load more',
  retry: 'Retry',
  signInTitle: 'Sign in required',
  signInBody: 'Sign in to view published workouts.',
  signInAction: 'Sign in',
  emptyTitle: 'No workout posts yet',
  emptyBody: 'Published workouts from this profile will appear here.',
  privateTitle: 'Private profile',
  privateBody: 'Follow approval is required before viewing this profile’s workout posts.',
  blockedTitle: 'Posts unavailable',
  blockedBody: 'These workout posts cannot be viewed because a block is active.',
  notFoundTitle: 'Workout posts not found',
  notFoundBody: 'The profile or workout post no longer exists.',
  loadErrorTitle: 'Could not load workout posts',
  loadErrorOffline: 'Connect to the internet and try again.',
  loadErrorSession: 'Your session expired. Sign in again.',
  loadErrorCursor: 'This page expired. Reload the posts from the beginning.',
  loadErrorGeneric: 'Workout posts could not be loaded right now.',
  openPost: 'Open workout post',
  untitledWorkout: 'Workout',
  duration: 'Duration',
  minutes: 'min',
  exercises: 'Exercises',
  sets: 'Sets',
  volume: 'Volume',
  weight: 'Weight',
  reps: 'Reps',
  rpe: 'RPE',
  noDetails: 'No workout details were shared.',
  noCaption: 'No caption.',
  reactionTitle: 'Reactions',
  reactionBody: 'Show support for this published workout.',
  reactionLoading: 'Loading reactions…',
  react: 'Like',
  reacted: 'Liked',
  reactionAddHint: 'Adds your reaction to this workout post.',
  reactionRemoveHint: 'Removes your reaction from this workout post.',
  reactionLoadOffline: 'Connect to the internet to load reactions.',
  reactionLoadSession: 'Your session expired. Sign in again.',
  reactionLoadGeneric: 'Reactions could not be loaded right now.',
  reactionUpdateError: 'Your reaction could not be updated. Try again.',
  deletePost: 'Delete post',
  deleteTitle: 'Delete this workout post?',
  deleteBody: 'The published snapshot will be permanently removed. Your private workout is not changed.',
  deleteConfirm: 'Delete',
  deleteError: 'The workout post could not be deleted. Try again.',
  deletedTitle: 'Post deleted',
  deletedBody: 'The published workout snapshot was removed.',
} as const;

export type SocialWorkoutPostSurfaceCopy = Record<keyof typeof en, string>;

const ru: SocialWorkoutPostSurfaceCopy = {
  postsAction: 'Опубликованные тренировки',
  listEyebrow: 'СОЦИАЛЬНЫЕ ТРЕНИРОВКИ',
  listTitle: 'Опубликованные тренировки',
  listSubtitle: 'Публичные снимки тренировок этого профиля.',
  detailEyebrow: 'ПУБЛИКАЦИЯ ТРЕНИРОВКИ',
  loading: 'Загрузка публикаций…',
  loadingPost: 'Загрузка публикации…',
  loadMore: 'Загрузить ещё',
  retry: 'Повторить',
  signInTitle: 'Требуется вход',
  signInBody: 'Войдите, чтобы просматривать опубликованные тренировки.',
  signInAction: 'Войти',
  emptyTitle: 'Публикаций пока нет',
  emptyBody: 'Опубликованные тренировки этого профиля появятся здесь.',
  privateTitle: 'Закрытый профиль',
  privateBody: 'Для просмотра публикаций требуется подтверждённая подписка.',
  blockedTitle: 'Публикации недоступны',
  blockedBody: 'Публикации нельзя просмотреть из-за активной блокировки.',
  notFoundTitle: 'Публикации не найдены',
  notFoundBody: 'Профиль или публикация больше не существует.',
  loadErrorTitle: 'Не удалось загрузить публикации',
  loadErrorOffline: 'Подключитесь к интернету и повторите попытку.',
  loadErrorSession: 'Сессия истекла. Войдите снова.',
  loadErrorCursor: 'Страница устарела. Загрузите публикации сначала.',
  loadErrorGeneric: 'Сейчас не удалось загрузить публикации тренировок.',
  openPost: 'Открыть публикацию',
  untitledWorkout: 'Тренировка',
  duration: 'Длительность',
  minutes: 'мин',
  exercises: 'Упражнения',
  sets: 'Подходы',
  volume: 'Объём',
  weight: 'Вес',
  reps: 'Повторения',
  rpe: 'RPE',
  noDetails: 'Подробности тренировки не опубликованы.',
  noCaption: 'Описание не добавлено.',
  reactionTitle: 'Реакции',
  reactionBody: 'Поддержите опубликованную тренировку.',
  reactionLoading: 'Загрузка реакций…',
  react: 'Нравится',
  reacted: 'Понравилось',
  reactionAddHint: 'Добавляет вашу реакцию к этой публикации.',
  reactionRemoveHint: 'Удаляет вашу реакцию с этой публикации.',
  reactionLoadOffline: 'Подключитесь к интернету, чтобы загрузить реакции.',
  reactionLoadSession: 'Сессия истекла. Войдите снова.',
  reactionLoadGeneric: 'Сейчас не удалось загрузить реакции.',
  reactionUpdateError: 'Не удалось обновить реакцию. Повторите попытку.',
  deletePost: 'Удалить публикацию',
  deleteTitle: 'Удалить публикацию тренировки?',
  deleteBody: 'Публичный снимок будет удалён навсегда. Приватная тренировка не изменится.',
  deleteConfirm: 'Удалить',
  deleteError: 'Не удалось удалить публикацию. Повторите попытку.',
  deletedTitle: 'Публикация удалена',
  deletedBody: 'Публичный снимок тренировки удалён.',
};

export const getSocialWorkoutPostSurfaceCopy = (
  locale: SupportedLocale,
): SocialWorkoutPostSurfaceCopy => (locale === 'ru' ? ru : en);
