import type { SupportedLocale } from '@/localization';

const en = {
  eyebrow: 'SOCIAL NETWORK',
  title: 'Your network',
  subtitle: 'Manage followers, subscriptions, and private-profile requests.',
  followers: 'Followers',
  following: 'Following',
  incoming: 'Requests',
  outgoing: 'Sent',
  loading: 'Loading profiles…',
  loadMore: 'Load more',
  retry: 'Retry',
  signInTitle: 'Sign in required',
  signInBody: 'Sign in to manage your social network.',
  signInAction: 'Sign in',
  emptyFollowersTitle: 'No followers yet',
  emptyFollowersBody: 'Profiles that follow you will appear here.',
  emptyFollowingTitle: 'Not following anyone',
  emptyFollowingBody: 'Profiles you follow will appear here.',
  emptyIncomingTitle: 'No follow requests',
  emptyIncomingBody: 'New requests for a private profile will appear here.',
  emptyOutgoingTitle: 'No pending requests',
  emptyOutgoingBody: 'Requests you send to private profiles will appear here.',
  loadErrorTitle: 'Could not load this list',
  loadErrorOffline: 'Connect to the internet and try again.',
  loadErrorSession: 'Your session expired. Sign in again.',
  loadErrorCursor: 'This page expired. Reload the list from the beginning.',
  loadErrorGeneric: 'The social list could not be loaded right now.',
  actionError: 'The social action could not be completed. Reload and try again.',
  approve: 'Approve',
  reject: 'Reject',
  cancel: 'Cancel request',
  unfollow: 'Unfollow',
  openProfile: 'Open profile',
  privateProfile: 'Private profile',
  publicProfile: 'Public profile',
  entryAction: 'Manage social network',
} as const;

export type SocialRelationshipListsCopy = Record<keyof typeof en, string>;

const ru: SocialRelationshipListsCopy = {
  eyebrow: 'СОЦИАЛЬНАЯ СЕТЬ',
  title: 'Ваши связи',
  subtitle: 'Управляйте подписчиками, подписками и запросами закрытых профилей.',
  followers: 'Подписчики',
  following: 'Подписки',
  incoming: 'Запросы',
  outgoing: 'Отправленные',
  loading: 'Загрузка профилей…',
  loadMore: 'Загрузить ещё',
  retry: 'Повторить',
  signInTitle: 'Требуется вход',
  signInBody: 'Войдите, чтобы управлять социальными связями.',
  signInAction: 'Войти',
  emptyFollowersTitle: 'Подписчиков пока нет',
  emptyFollowersBody: 'Профили, подписанные на вас, появятся здесь.',
  emptyFollowingTitle: 'Подписок пока нет',
  emptyFollowingBody: 'Профили, на которые вы подпишетесь, появятся здесь.',
  emptyIncomingTitle: 'Нет запросов на подписку',
  emptyIncomingBody: 'Новые запросы к закрытому профилю появятся здесь.',
  emptyOutgoingTitle: 'Нет ожидающих запросов',
  emptyOutgoingBody: 'Отправленные запросы к закрытым профилям появятся здесь.',
  loadErrorTitle: 'Не удалось загрузить список',
  loadErrorOffline: 'Подключитесь к интернету и повторите попытку.',
  loadErrorSession: 'Сессия истекла. Войдите снова.',
  loadErrorCursor: 'Эта страница устарела. Загрузите список сначала.',
  loadErrorGeneric: 'Сейчас не удалось загрузить социальный список.',
  actionError: 'Не удалось выполнить действие. Обновите список и повторите попытку.',
  approve: 'Подтвердить',
  reject: 'Отклонить',
  cancel: 'Отменить запрос',
  unfollow: 'Отписаться',
  openProfile: 'Открыть профиль',
  privateProfile: 'Закрытый профиль',
  publicProfile: 'Публичный профиль',
  entryAction: 'Управлять социальными связями',
};

export const getSocialRelationshipListsCopy = (
  locale: SupportedLocale,
): SocialRelationshipListsCopy => (locale === 'ru' ? ru : en);
